baseURL = 'https://rootsoftware.dev/'
languageCode = 'en-us'
title = 'Root Software'

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 10

[[menus.main]]
name = 'Services'
pageRef = '/'
weight = 20

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
